name: Grupo4

on:
  push:
    branches:
      - main

env:
  GRUPO: "Grupo 4"
  CURSO: "Herramientas de Desarrollo"
  DESPEDIDA: "SI"

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Prueba de mensajes
        run: echo "Hola Grupo 4, bienvenidos a GitHub Actions"
